apiVersion: v1
kind: Service
metadata:
  labels:
    app: TestAppsrv
    service: TestAppsrv
  name: TestAppsrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: TestApp